### PR TITLE
fix SACSegmentation cell

### PR DESCRIPTION
**Pull request by v4hn**
It would be great if you could do a release to include this fix and Sven's new parameter.

### CODE REVIEW

**Comment by v4hn** [comment]
I've added an additional (orthogonal) patch to this request, because the diff is based on the fix.

The second (and third) commits add indices-support for both SACSegmentation cells.

**Comment by v4hn** [comment]
@vrabaud: Can I do anything to get these merged soon?
It's rather cumbersome to tell people to use a custom fork of ecto_pcl in order to use a software module...

**Comment by vrabaud** [comment]
wow, can't believe I missed that one. Sorry, releasing now.

**Comment by v4hn** [comment]
Thanks a lot!

**Comment by vrabaud** [comment]
done

**Pull request merged**
