### PR TITLE
fix samples.

### PR DESCRIPTION
**Pull request by jihoonl**
But still pcd_viewer gets segmentation fault in 16.04

### CODE REVIEW

**Comment by vrabaud** [comment]
Hmm, is pcd_viewer something you need? We could do the same in OpenCV3 now.

**Comment by jihoonl** [comment]
I just wanted to have a working 3d visualizer. Can you guide me how to do it with OpenCV3?

**Comment by vrabaud** [comment]
we don't have a cell yet but you could create one in ecto_image_pipeline. Then, just use: 
http://docs.opencv.org/master/d7/df9/tutorial_table_of_content_viz.html
with a cloud: http://docs.opencv.org/master/db/d82/classcv_1_1viz_1_1WCloud.html

**Comment by jihoonl** [comment]
Alright. Thanks!

**Pull request merged**
